# Conexión a Neon PostgreSQL para EcoPredict
spring.datasource.url=jdbc:postgresql://ep-winter-block-apibx7ta-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6xHi1UEkcSqZ

# Driver necesario para PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para crear/actualizar tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect